CREATE DATABASE IF NOT EXISTS Product_db CHARACTER SET 'utf8';

USE Product_db;

CREATE TABLE IF NOT EXISTS Product(
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
name VARCHAR(150) NOT NULL UNIQUE,
description TEXT NOT NULL,
category VARCHAR(100) NOT NULL,
store VARCHAR(100) NOT NULL,
url VARCHAR(500) NOT NULL
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Save(
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
id_food INT UNSIGNED NOT NULL,
id_new_product INT UNSIGNED NOT NULL
)
ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS Category(
id INT UNSIGNED AUTO_INCREMENT NOT NULL PRIMARY KEY,
category VARCHAR(100) NOT NULL UNIQUE
)
ENGINE = InnoDB;

ALTER TABLE Save
ADD CONSTRAINT fk_save_id FOREIGN KEY (id_food) REFERENCES Product (id);

ALTER TABLE Save
ADD CONSTRAINT fk_save_new_product FOREIGN KEY (id_new_product) REFERENCES Product (id);